var data = [{
  "id": 1,
  "src": "images/img-22.jpg",
  "srcmobile": "images/img-22-m.jpg",
  "title": "UNTITLED 22",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "53 x 35 cm (20 x 14 in)",
},
{
  "id": 2,
  "src": "images/img-23.jpg",
  "srcmobile": "images/img-23-m.jpg",
  "title": "UNTITLED 23",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "27 x 26 cm (10 x 11 in)",
},
{
  "id": 3,
  "src": "images/img-24.jpg",
  "srcmobile": "images/img-24-m.jpg",
  "title": "UNTITLED 24",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "28 x 29 cm (11 x 11 in)",
},
{
  "id": 4,
  "src": "images/img-25.jpg",
  "srcmobile": "images/img-25-m.jpg",
  "title": "UNTITLED 25",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "50 x 53 cm (19 x 20 in)",
},
{
  "id": 5,
  "src": "images/img-26.jpg",
  "srcmobile": "images/img-26-m.jpg",
  "title": "UNTITLED 26",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "44 x 46 cm (17 x 18 in)",
},
{
  "id": 6,
  "src": "images/img-27.jpg",
  "srcmobile": "images/img-27-m.jpg",
  "title": "UNTITLED 27",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "33 x 27 cm (13 x 11 in)",
},
{
  "id": 7,
  "src": "images/img-28.jpg",
  "srcmobile": "images/img-28-m.jpg",
  "title": "UNTITLED 28",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "34 x 35 cm (14 x 14 in)",
},
{
  "id": 8,
  "src": "images/img-29.jpg",
  "srcmobile": "images/img-29-m.jpg",
  "title": "UNTITLED 29",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "48 x 29 cm (19 x 11 in)",
},
{
  "id": 9,
  "src": "images/img-32.jpg",
  "srcmobile": "images/img-32-m.jpg",
  "title": "UNTITLED 32",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "21 x 25 cm (8 x 10 in)",
},
{
  "id": 10,
  "src": "images/img-48.jpg",
  "srcmobile": "images/img-48-m.jpg",
  "title": "UNTITLED 48",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "40 x 37 cm (16 x 15 in)",
},
{
  "id": 11,
  "src": "images/img-49.jpg",
  "srcmobile": "images/img-49-m.jpg",
  "title": "UNTITLED 49",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "58 x 46 cm (23 x 18 in)",
},
{
  "id": 12,
  "src": "images/img-50.jpg",
  "srcmobile": "images/img-50-m.jpg",
  "title": "UNTITLED 50",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "36 x 30 cm (14 x 12 in)",
},
{
  "id": 13,
  "src": "images/img-51.jpg",
  "srcmobile": "images/img-51-m.jpg",
  "title": "UNTITLED 51",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "57 x 44 cm (22 x 17 in)",
},
{
  "id": 14,
  "src": "images/img-52.jpg",
  "srcmobile": "images/img-52-m.jpg",
  "title": "UNTITLED 52",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "54 x 38 cm (21 x 15 in)",
},
{
  "id": 15,
  "src": "images/img-53.jpg",
  "srcmobile": "images/img-53-m.jpg",
  "title": "UNTITLED 53",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "33 x 35 cm (13 x 14 in)",
},
{
  "id": 16,
  "src": "images/img-54.jpg",
  "srcmobile": "images/img-54-m.jpg",
  "title": "UNTITLED 54",
  "year": "2016",
  "type": "collage",
  "place": "East Hampton",
  "dimensions" : "43 x 33 cm (17 x 13 in)",
},
{
  "id": 17,
  "src": "images/img-55.jpg",
  "srcmobile": "images/img-55-m.jpg",
  "title": "UNTITLED 55",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "49 x 39 cm (19 x 15 in)",
},
{
  "id": 18,
  "src": "images/img-56.jpg",
  "srcmobile": "images/img-56-m.jpg",
  "title": "UNTITLED 56",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "52 x 51 cm (20 x 20 in)",
},
{
  "id": 19,
  "src": "images/img-57.jpg",
  "srcmobile": "images/img-57-m.jpg",
  "title": "UNTITLED 57",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "39 x 32 cm (15 x 13 in)",
},
{
  "id": 20,
  "src": "images/img-58.jpg",
  "srcmobile": "images/img-58-m.jpg",
  "title": "UNTITLED 58",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "51 x 29 cm (20 x 11 in)",
},
{
  "id": 21,
  "src": "images/img-59.jpg",
  "srcmobile": "images/img-59-m.jpg",
  "title": "UNTITLED 59",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "40 x 34 cm (16 x 13 in)",
},
{
  "id": 22,
  "src": "images/img-60.jpg",
  "srcmobile": "images/img-60-m.jpg",
  "title": "UNTITLED 60",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "36 x 39 cm (14 x 15 in)",
},
{
  "id": 23,
  "src": "images/img-61.jpg",
  "srcmobile": "images/img-61-m.jpg",
  "title": "UNTITLED 61",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "39 x 28 cm (15 x 11 in)",
},
{
  "id": 24,
  "src": "images/img-62.jpg",
  "srcmobile": "images/img-62-m.jpg",
  "title": "UNTITLED 62",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "35 x 32 cm (14 x 12 in)",
},
{
  "id": 25,
  "src": "images/img-63.jpg",
  "srcmobile": "images/img-63-m.jpg",
  "title": "UNTITLED 63",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "53 x 27 cm (21 x 11 in)",
},
{
  "id": 26,
  "src": "images/img-64.jpg",
  "srcmobile": "images/img-64-m.jpg",
  "title": "UNTITLED 64",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "57 x 33 cm (22 x 13 in)",
},
{
  "id": 27,
  "src": "images/img-65.jpg",
  "srcmobile": "images/img-65-m.jpg",
  "title": "UNTITLED 65",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "38 x 30 cm (15 x 12 in)",
},
{
  "id": 28,
  "src": "images/img-67.jpg",
  "srcmobile": "images/img-67-m.jpg",
  "title": "UNTITLED 67",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "49 x 41 cm (19 x 16 in)",
},
{
  "id": 29,
  "src": "images/img-68.jpg",
  "srcmobile": "images/img-68-m.jpg",
  "title": "UNTITLED 68",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "60 x 43 cm (23 x 17 in)",
},
{
  "id": 30,
  "src": "images/img-69.jpg",
  "srcmobile": "images/img-69-m.jpg",
  "title": "UNTITLED 69",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "37 x 38 cm (14 x 14 in)",
},
{
  "id": 31,
  "src": "images/img-70.jpg",
  "srcmobile": "images/img-70-m.jpg",
  "title": "UNTITLED 70",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "42 x 39 cm (16 x 15 in)",
},
{
  "id": 32,
  "src": "images/img-71.jpg",
  "srcmobile": "images/img-71-m.jpg",
  "title": "UNTITLED 71",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "54 x 39 cm (21 x 15 in)",
},
{
  "id": 33,
  "src": "images/img-72.jpg",
  "srcmobile": "images/img-72-m.jpg",
  "title": "UNTITLED 72",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "44 x 45 cm (17 x 17 in)",
},
{
  "id": 34,
  "src": "images/img-73.jpg",
  "srcmobile": "images/img-73-m.jpg",
  "title": "UNTITLED 73",
  "year": "2016",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "46 x 45 cm (18 x 18 in)",
},
{
  "id": 35,
  "src": "images/img-74.jpg",
  "srcmobile": "images/img-74-m.jpg",
  "title": "UNTITLED 74",
  "year": "2016",
  "type": "collage",
  "place": "Le Logeo",
  "dimensions" : "59 x 40 cm (23 x 15 in)",
},
{
  "id": 36,
  "src": "images/img-75.jpg",
  "srcmobile": "images/img-75-m.jpg",
  "title": "UNTITLED 75",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "61 x 50 cm (24 x 20 in)",
},
{
  "id": 37,
  "src": "images/img-76.jpg",
  "srcmobile": "images/img-76-m.jpg",
  "title": "UNTITLED 76",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "57 x 45 cm (22 x 18 in)",
},
{
  "id": 38,
  "src": "images/img-77.jpg",
  "srcmobile": "images/img-77-m.jpg",
  "title": "UNTITLED 77",
  "year": "2016",
  "type": "collage",
  "place": "New York",
  "dimensions" : "46 x 37 cm (18 x 14 in)",
},
{
  "id": 39,
  "src": "images/img-78.jpg",
  "srcmobile": "images/img-78-m.jpg",
  "title": "UNTITLED 78",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "27 x 31 cm (10 x 12 in)",
},
{
  "id": 40,
  "src": "images/img-79.jpg",
  "srcmobile": "images/img-79-m.jpg",
  "title": "UNTITLED 79",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "36 x 29 cm (14 x 11 in)",
},
{
  "id": 41,
  "src": "images/img-80.jpg",
  "srcmobile": "images/img-80-m.jpg",
  "title": "UNTITLED 80",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "58 x 41 cm (23 x 16 in)",
},
{
  "id": 42,
  "src": "images/img-81.jpg",
  "srcmobile": "images/img-81-m.jpg",
  "title": "UNTITLED 81",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "41 x 30 cm (16 x 12 in)",
},
{
  "id": 43,
  "src": "images/img-82.jpg",
  "srcmobile": "images/img-82-m.jpg",
  "title": "UNTITLED 82",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "39 x 33 cm (15 x 13 in)",
},
{
  "id": 44,
  "src": "images/img-83.jpg",
  "srcmobile": "images/img-83-m.jpg",
  "title": "UNTITLED 83",
  "year": "2016",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "51 x 35 cm (20 x 13 in)",
},
{
  "id": 45,
  "src": "images/img-84.jpg",
  "srcmobile": "images/img-84-m.jpg",
  "title": "UNTITLED 84",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "64 x 34 cm (25 x 13 in)",
},
{
  "id": 46,
  "src": "images/img-85.jpg",
  "srcmobile": "images/img-85-m.jpg",
  "title": "UNTITLED 85",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "28 x 33 cm (11 x 13 in)",
},
{
  "id": 47,
  "src": "images/img-86.jpg",
  "srcmobile": "images/img-86-m.jpg",
  "title": "UNTITLED 86",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "26 x 21 cm (10 x 8 in)",
},
{
  "id": 48,
  "src": "images/img-87.jpg",
  "srcmobile": "images/img-87-m.jpg",
  "title": "UNTITLED 87",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "46 x 27 cm (18 x 10 in)",
},
{
  "id": 49,
  "src": "images/img-88.jpg",
  "srcmobile": "images/img-88-m.jpg",
  "title": "UNTITLED 88",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "34 x 36 cm (13 x 14 in)",
},
{
  "id": 50,
  "src": "images/img-89.jpg",
  "srcmobile": "images/img-89-m.jpg",
  "title": "UNTITLED 89",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "46 x 29 cm (18 x 12 in)",
},
{
  "id": 51,
  "src": "images/img-90.jpg",
  "srcmobile": "images/img-90-m.jpg",
  "title": "UNTITLED 90",
  "year": "2017",
  "type": "collage",
  "place": "New York",
  "dimensions" : "52 x 18 cm (20 x 7 in)",
},
{
  "id": 52,
  "src": "images/img-94.jpg",
  "srcmobile": "images/img-94-m.jpg",
  "title": "UNTITLED 94",
  "year": "2015",
  "type": "collage",
  "place": "New York",
  "dimensions" : "34 x 25 cm (13 x 10 in)",
},
{
  "id": 53,
  "src": "images/img-soleilendommage.jpg",
  "srcmobile": "images/img-soleilendommage-m.jpg",
  "title": "SOLEIL ENDOMMAGÉ",
  "year": "2017",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "49 x 27 cm (19 x 10 in)",
},
{
  "id": 54,
  "src": "images/img-lesignaldelhommeseul.jpg",
  "srcmobile": "images/img-lesignaldelhommeseul-m.jpg",
  "title": "LE SIGNAL DE L'HOMME SEUL",
  "year": "2017",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "25 x 29 cm (10 x 11 in)",
},
{
  "id": 55,
  "src": "images/img-glamouretmort.jpg",
  "srcmobile": "images/img-glamouretmort-m.jpg",
  "title": "GLAMOUR ET MORT",
  "year": "2017",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "32 x 29 cm (12 x 11 in)",
},
{
  "id": 56,
  "src": "images/img-letheatreduchaman.jpg",
  "srcmobile": "images/img-letheatreduchaman-m.jpg",
  "title": "LE THÉÂTRE DU CHAMAN",
  "year": "2017",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "34 x 29 cm (13 x 11 in)",
},
{
  "id": 57,
  "src": "images/img-morceauxdeglaceetdecharbon.jpg",
  "srcmobile": "images/img-morceauxdeglaceetdecharbon-m.jpg",
  "title": "MORCEAUX DE GLACE ET DE CHARBON",
  "year": "2017",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "28 x 30 cm (11 x 12 in)",
},
{
  "id": 58,
  "src": "images/img-latisserie.jpg",
  "srcmobile": "images/img-latisserie-m.jpg",
  "title": "LA TISSERIE",
  "year": "2017",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "unknown dimensions",
},
{
  "id": 59,
  "src": "images/img-alambicpourlesthes.jpg",
  "srcmobile": "images/img-alambicpourlesthes-m.jpg",
  "title": "ALAMBIC POUR LES THÉS",
  "year": "2017",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "unknown dimensions",
},
{
  "id": 60,
  "src": "images/img-91.jpg",
  "srcmobile": "images/img-91-m.jpg",
  "title": "UNTITLED 91",
  "year": "2017",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "unknown dimensions",
},
{
  "id": 61,
  "src": "images/img-rebondissements.jpg",
  "srcmobile": "images/img-rebondissements-m.jpg",
  "title": "REBONDISSEMENTS",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "unknown dimensions",
},
{
  "id": 62,
  "src": "images/img-jambesroyales.jpg",
  "srcmobile": "images/img-jambesroyales-m.jpg",
  "title": "JAMBES ROYALES",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "30 x 37 cm (12 x 15 in)",
},
{
  "id": 63,
  "src": "images/img-vaguesaberrantes.jpg",
  "srcmobile": "images/img-vaguesaberrantes-m.jpg",
  "title": "VAGUES ABERRANTES",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "53 x 37 cm (21 x 15 in)",
},
{
  "id": 64,
  "src": "images/img-92.jpg",
  "srcmobile": "images/img-92-m.jpg",
  "title": "UNTITLED 92",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "47 x 31 cm (19 x 12 in)",
},
{
  "id": 65,
  "src": "images/img-lapropagationdescristaux.jpg",
  "srcmobile": "images/img-lapropagationdescristaux-m.jpg",
  "title": "LA PROPAGATION DES CRISTAUX",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "54 x 39 cm (21 x 15 in)",
},
{
  "id": 66,
  "src": "images/img-tueslestous.jpg",
  "srcmobile": "images/img-tueslestous-m.jpg",
  "title": "TUEZ-LES TOUS",
  "year": "2018",
  "type": "assemblage",
  "place": "Paris",
  "dimensions" : "27 cm (11 in)",
},
{
  "id": 67,
  "src": "images/img-leplongeondelasirene.jpg",
  "srcmobile": "images/img-leplongeondelasirene-m.jpg",
  "title": "LE PLONGEON DE LA SIRÈNE",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "23 x 29 cm (9 x 11 in)",
},
{
  "id": 68,
  "src": "images/img-soleilsurmarecage.jpg",
  "srcmobile": "images/img-soleilsurmarecage-m.jpg",
  "title": "SOLEIL SUR MARÉCAGE",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "29 x 28 cm (11 x 11 in)",
},
{
  "id": 69,
  "src": "images/img-lamachoiredelabaleine.jpg",
  "srcmobile": "images/img-lamachoiredelabaleine-m.jpg",
  "title": "LA MÂCHOIRE DE LA BALEINE",
  "year": "2018",
  "type": "collage",
  "place": "Paris",
  "dimensions" : "43 x 33 cm (17 x 13 in)",},
{
  "id": 70,
  "src": "images/img-cieldavril.jpg",
  "srcmobile": "images/img-cieldavril-m.jpg",
  "title": "CIEL D'AVRIL",
  "year": "2020",
  "type": "collage",
  "place": "Bozel",
  "dimensions" : "66 x 38 cm (26 x 15 in)",
}]